runtime: python27
api_version: 1
threadsafe: true
instance_class: F1

handlers:

- url: /.*
  script: main.app
  secure: always
  redirect_http_response_code: 301

libraries:
- name: grpcio
  version: 1.0.0

vpc_access_connector:
  name: <FILL IN HERE>

env_variables:
  REDIS_CACHE_URL: <FILL IN HERE>

